# -*- coding: utf-8 -*-

{
    'name': 'Jakc Labs - Workshop Work Order',
    'version': '9.0.0.1.0',
    'category': 'Workshop',
    'license': 'AGPL-3',
    'summary': 'Workshop Work Order',
    'author': "Jakc Labs",
    'website': 'http://www.jakc-labs.com/',
    'depends': [
        'account',
        'sale',
        'stock',
        'purchase',
        'hr',
        'hr_payroll',
        'mrp',
        'mrp_operations',
        'mrp_hook',
        'mrp_operations_extension',
        'jakc_workshop',
        'jakc_res_partner',
        'jakc_hr',
    ],
    'data': [
        'wizard/add_operator_view.xml',
        'wizard/add_image_view.xml',
        'wizard/consume_material_view.xml',
        'wizard/add_material_view.xml',
        'wizard/add_other_material_view.xml',
        'wizard/cancel_material_view.xml',
        'wizard/return_material_view.xml',
        'wizard/process_operator_fee_view.xml',
        'wizard/process_sparepart_view.xml',
        'wizard/return_sparepart_view.xml',
        'wizard/stock_move_view.xml',
        'wizard/add_order_line_view.xml',
        'wizard/approve_workcenter_line_view.xml',
        'wizard/report_sale_workorder_view.xml',
        'wizard/report_operator_fee_view.xml',
        'wizard/report_consume_material_view.xml',
        'wizard/report_sale_workorder_view.xml',
        'views/jakc_sale_view.xml',
        'views/jakc_sale_report.xml',
        'views/jakc_sale_dashboard.xml',
        'views/jakc_product_view.xml',
        'views/templates.xml',
        'views/jakc_sale_sequence.xml',
        'views/res_company_view.xml',
        'views/res_partner_view.xml',
        'views/mrp_view.xml',
        'views/mrp_workflow.xml',
        'views/hr_view.xml',
        'security/ir.model.access.csv',
        'report/report_account_invoice_summary.xml',
        'report/report_account_invoice_summary_templates.xml',
        'report/report_account_invoice_or.xml',
        'report/report_account_invoice_or_templates.xml',
        'report/report_car_status.xml',
        'report/report_car_status_templates.xml',
        'report/sale_order_workshop_report.xml',
        'report/sale_order_workshop_report_templates.xml',
        'report/report_workorder_report.xml',
        'report/report_workorder_template.xml',
        'report/report_operator_fee_template.xml',
        'report/report_consume_material_report.xml',
        'report/report_consume_material_template.xml',

    ],
    'installable': True,
    'application': True,
}
